name:                llm-tests
version:             0.1.0.0
description:         "llm-tests"

dependencies:
- base >= 4.7 && < 5
- text
- containers
- nonempty-containers
- async
- optparse-applicative
- aeson
- aeson-pretty
- safe
- either
- megaparsec
- witherable
- ansi-terminal
- envparse
- neat-interpolation

default-extensions:
- OverloadedStrings

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wunused-packages
  - -O2

library:
  source-dirs: src

executables:
  llm-tests:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llm-tests

tests:
  llm-tests-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0 # No optimization for faster test runs
    dependencies:
    - llm-tests
    - hspec
    - QuickCheck
    build-tools:
    - hspec-discover

verbatim:
  cabal-version: 3.0
